
[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "integration_tests",
    "lib",
    "main",
    "player_state",
    "time",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.8.0"
bevy-inspector-egui = "0.13.0"
bevy_hanabi = "0.4.0"
rand = "0.8.5"
map-macro = "0.2.3"
strum = "0.24.1"
strum_macros = "0.24.2"
