
[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "integration_tests",
    "lib",
    "main",
    "player_state",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy_hanabi = "0.8.0"
bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
rand = "0.8"
strum = "0.25.0"
strum_macros = "0.25.2"
clap = { version = "4.1.7", features = ["derive"] }
bevy-scene-hook = "9.0.0"
