[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "lib",
    "main",
    "player_state",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.14"
bevy_hanabi = "0.12"
bevy-inspector-egui = "0.25"

rand = "0.8"
strum = "0.26"
strum_macros = "0.26"
clap = { version = "4.5", features = ["derive"] }
