
[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "integration_tests",
    "lib",
    "main",
    "player_state",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy_hanabi = { git = "https://github.com/djeedai/bevy_hanabi" } # Because not updated to work with bevy 0.12.0 yet, should be 0.8 when it does
bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
rand = "0.8"
map-macro = "0.2"
strum = "0.25.0"
strum_macros = "0.25.2"
clap = { version = "4.1.7", features = ["derive"] }
