[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "lib",
    "main",
    "player_state",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy_hanabi = "0.10.0"
bevy = "0.13.0"
bevy-inspector-egui = "0.23.2"
rand = "0.8"
strum = "0.26.1"
strum_macros = "0.26.1"
clap = { version = "4.5.1", features = ["derive"] }
bevy-scene-hook = "10.0.0"
