
[workspace]
resolver = "2"
members = [
    "characters",
    "input_parsing",
    "integration_tests",
    "lib",
    "main",
    "player_state",
    "wag_args",
    "wag_core",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = "0.9"
bevy-inspector-egui = "0.17"
bevy_hanabi = "0.5"
rand = "0.8"
map-macro = "0.2"
strum = "0.24"
strum_macros = "0.24"
clap = {version = "4.1.7", features = ["derive"] }
