[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "warnings", "--emit=dep-info,metadata"]

[tasks.test]
command = "cargo"
args = ["test", "--tests"]

[tasks.udeps]
install_crate = "cargo-udeps"
command = "cargo"
args = ["udeps"]

[tasks.quick-validate]
run_task = { name = ["check", "format", "clippy", "test"] }

[tasks.full-validate]
run_task = { name = ["check", "format", "clippy", "test", "udeps"] }

[tasks.dev-local]
command = "cargo"
args = ["run", "--", "local", "0", "69", "samurai", "samurai", "0"]

[tasks.dev-online]
command = "cargo"
args = ["run", "--", "online", "69", "samurai"]

[tasks.dev-synctest]
command = "cargo"
args = ["run", "--", "synctest", "69", "samurai"]

[tasks.prod]
command = "cargo"
args = ["run"]

[tasks.release-build]
command = "cargo"
args = ["build", "--release"]

[tasks.assemble-package]
script_runner = "@shell"
script = '''
rm -fr package
mkdir package
cp target/release/whoops-all-grapplers package
cp -r main/assets package
'''

# "package" is already taken by cargo-make for some reason
# This is useful for testing on the steam deck
[tasks.update-package]
run_task = { name = ["release-build", "assemble-package"] }
