
[workspace]
resolver = "2"
members = [
    "constants",
    "input_parsing",
    "integration_tests",
    "lib",
    "main",
    "moves",
    "player_state",
    "types",
    "time",
]

[profile.dev]
debug = 1
lto = "off"
incremental = true
