[package]
name = "input_parsing"
version = "0.1.0"
edition = "2018"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.5.0"
bevy-inspector-egui = "0.6.1"

types = { path = "../types" }
