[package]
name = "whoops-all-grapplers"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.8.0"

whoops-all-grapplers-lib = { path = "../lib" }

