[package]
name = "whoops-all-grapplers"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = { workspace = true }

whoops-all-grapplers-lib = { path = "../lib" }
wag_core = { path = "../wag_core" }

bitt = { workspace = true }
