[package]
name = "time"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = { workspace = true }
bevy-inspector-egui = { workspace = true }

core = { path = "../core" }
