[package]
name = "moves"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.6.0"
bevy-inspector-egui = "0.7.6"

types = { path = "../types" }
constants = { path = "../constants" }
