[package]
name = "moves"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.6.1"
bevy-inspector-egui = "0.8.2"
bitflags = "1.3.2"

types = { path = "../types" }
constants = { path = "../constants" }
