[package]
name = "moves"
version = "0.1.0"
edition = "2018"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy-inspector-egui = "0.6.1"
bevy="0.5.0"

types = { path = "../types" }
constants = { path = "../constants" }
