[package]
name = "time"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.6.1"
bevy-inspector-egui = "0.9.0"
mock_instant = { version = "0.2", features = ["sync"] }

constants = { path = "../constants" }
types = { path = "../types" }
