[package]
name = "kits"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.6.1"
bevy-inspector-egui = "0.8.2"

constants = { path = "../constants" }
types = { path = "../types" }
