[package]
name = "player_state"
version = "0.1.0"
edition = "2021"
authors = ["Eero Häihälä <eero.haihala@gmail.com>"]

[dependencies]
bevy = "0.6.1"
bevy-inspector-egui = "0.8.2"
strum = "0.23.0"

moves = { path = "../moves" }
types = { path = "../types" }
