name: Cargo make CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Run sanity check
        run: cargo make sanity_check

      - name: Save artefacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: sanity-tests-artefacts
          path: bitt/artefacts
