name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1

      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev libudev-dev

      - name: Install dev dependencies
        run: make install

      - name: Build
        run: make build

      - name: Run checks
        run: make check

      - name: Integration tests
        run: make integration
