name: Cargo make CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Install dependencies
        run: sudo apt-get update \
          && sudo apt-get install -y libasound2-dev libudev-dev \

      - name: Build
        run: cargo make build

      - name: Run checks
        run: cargo make validate
