name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev

      - name: Install dev dependencies
        run: make install

      - name: Build
        run: make build

      - name: Run checks
        run: make check

      # Integration tests failing in CI due to there being no GPU
      # There aren't that many of them and they don't really provide value, so for now just let them be there
      # Once the core game works, rework the integration tests
      # - name: Integration tests
      #   run: make integration
