name: Commit validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Install dependencies
        run: sudo apt-get update
          && sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Run checks
        run: cargo make full-validate
