name: Commit validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Install dependencies
        run: sudo apt-get update
          && sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev

      - name: Build
        run: cargo make build

      - name: Run checks
        run: cargo make validate

  BITT-sanity-check:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: client

      - name: Run sanity check
        run: cargo make release_sanity_check

      - name: Save artefacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: sanity-tests-artefacts
          path: client/bitt/artefacts
